# Site settings
title: "techArtJam"
email: chad@techartjam.com
description: Chad Moore is a former Technical Art Director in the video games business. Currently he coaches awesome people working in the intersection of art and technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://techartjam.github.io" # the base hostname & protocol for your site
twitter_username: techArtJam
github_username:  techArtJam

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: pygments

# Pagination
paginate: 10
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed
